all: libquantum libquantum.demo libquantum.quob

libquantum:

	$(MAKE) -C lib $@

libquantum.demo:

	$(MAKE) -C demo $@
	
libquantum.quob:

	$(MAKE) -C quob $@

clean:

	$(MAKE) -C lib $@
	$(MAKE) -C demo $@
	$(MAKE) -C quob $@